export { default as DeleteModal } from './DeleteModal'
export { default as HeaderTitle } from './HeaderTitle'
export { default as Loader } from './Loader'
export { default as Pagination } from './Pagination'
export { default as SearchForm } from './SearchForm'
